name: '${project.artifactId}'
main: com.mcmiddleearth.mcmetours.paper.ToursPaperPlugin
version: '${project.version}'
author: Jubo
api-version: 1.19
softdepend: [DiscordSRV]

permissions:
  Tours.admin:
    description: Admin permissions
    default: op
    children:
      Tours.ranger: true
  Tours.ranger:
    description: Tour Host permission
    default: op
    children:
      Tours.user: true
  Tours.user:
    description: allows to participate in tours
    default: op